package com.send.sms.pojo;

public class Detail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.taskID
     *
     * @mbggenerated
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.finalStatus
     *
     * @mbggenerated
     */
    private Integer finalstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.id
     *
     * @return the value of detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.id
     *
     * @param id the value for detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.taskID
     *
     * @return the value of detail.taskID
     *
     * @mbggenerated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.taskID
     *
     * @param taskid the value for detail.taskID
     *
     * @mbggenerated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.tel
     *
     * @return the value of detail.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.tel
     *
     * @param tel the value for detail.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.status
     *
     * @return the value of detail.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.status
     *
     * @param status the value for detail.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.finalStatus
     *
     * @return the value of detail.finalStatus
     *
     * @mbggenerated
     */
    public Integer getFinalstatus() {
        return finalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.finalStatus
     *
     * @param finalstatus the value for detail.finalStatus
     *
     * @mbggenerated
     */
    public void setFinalstatus(Integer finalstatus) {
        this.finalstatus = finalstatus;
    }
}