package com.send.sms.pojo;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.taskID
     *
     * @mbggenerated
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.telnum
     *
     * @mbggenerated
     */
    private Integer telnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.action_time
     *
     * @mbggenerated
     */
    private Date actionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.send_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date sendTime;   
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.sendCode
     *
     * @mbggenerated
     */
    private String sendcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.pre_cost
     *
     * @mbggenerated
     */
    private Float preCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.cost
     *
     * @mbggenerated
     */
    private BigDecimal cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.sucnum
     *
     * @mbggenerated
     */
    private Integer sucnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tasks.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.id
     *
     * @return the value of tasks.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.id
     *
     * @param id the value for tasks.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.username
     *
     * @return the value of tasks.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.username
     *
     * @param username the value for tasks.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.taskID
     *
     * @return the value of tasks.taskID
     *
     * @mbggenerated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.taskID
     *
     * @param taskid the value for tasks.taskID
     *
     * @mbggenerated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.telnum
     *
     * @return the value of tasks.telnum
     *
     * @mbggenerated
     */
    public Integer getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.telnum
     *
     * @param telnum the value for tasks.telnum
     *
     * @mbggenerated
     */
    public void setTelnum(Integer telnum) {
        this.telnum = telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.create_time
     *
     * @return the value of tasks.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.create_time
     *
     * @param createTime the value for tasks.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.action_time
     *
     * @return the value of tasks.action_time
     *
     * @mbggenerated
     */
    public Date getActionTime() {
        return actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.action_time
     *
     * @param actionTime the value for tasks.action_time
     *
     * @mbggenerated
     */
    public void setActionTime(Date actionTime) {
        this.actionTime = actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.send_time
     *
     * @return the value of tasks.send_time
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.send_time
     *
     * @param sendTime the value for tasks.send_time
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.sendCode
     *
     * @return the value of tasks.sendCode
     *
     * @mbggenerated
     */
    public String getSendcode() {
        return sendcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.sendCode
     *
     * @param sendcode the value for tasks.sendCode
     *
     * @mbggenerated
     */
    public void setSendcode(String sendcode) {
        this.sendcode = sendcode == null ? null : sendcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.pre_cost
     *
     * @return the value of tasks.pre_cost
     *
     * @mbggenerated
     */
    public Float getPreCost() {
        return preCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.pre_cost
     *
     * @param preCost the value for tasks.pre_cost
     *
     * @mbggenerated
     */
    public void setPreCost(Float preCost) {
        this.preCost = preCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.cost
     *
     * @return the value of tasks.cost
     *
     * @mbggenerated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.cost
     *
     * @param cost the value for tasks.cost
     *
     * @mbggenerated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.sucnum
     *
     * @return the value of tasks.sucnum
     *
     * @mbggenerated
     */
    public Integer getSucnum() {
        return sucnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.sucnum
     *
     * @param sucnum the value for tasks.sucnum
     *
     * @mbggenerated
     */
    public void setSucnum(Integer sucnum) {
        this.sucnum = sucnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.status
     *
     * @return the value of tasks.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.status
     *
     * @param status the value for tasks.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.content
     *
     * @return the value of tasks.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.content
     *
     * @param content the value for tasks.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tasks.remarks
     *
     * @return the value of tasks.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tasks.remarks
     *
     * @param remarks the value for tasks.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}