package com.send.sms.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.access_id
     *
     * @mbggenerated
     */
    private String accessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.access_key
     *
     * @mbggenerated
     */
    private String accessKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.access_secret
     *
     * @mbggenerated
     */
    private String accessSecret;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.access_id
     *
     * @return the value of user.access_id
     *
     * @mbggenerated
     */
    public String getAccessId() {
        return accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.access_id
     *
     * @param accessId the value for user.access_id
     *
     * @mbggenerated
     */
    public void setAccessId(String accessId) {
        this.accessId = accessId == null ? null : accessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.access_key
     *
     * @return the value of user.access_key
     *
     * @mbggenerated
     */
    public String getAccessKey() {
        return accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.access_key
     *
     * @param accessKey the value for user.access_key
     *
     * @mbggenerated
     */
    public void setAccessKey(String accessKey) {
        this.accessKey = accessKey == null ? null : accessKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.access_secret
     *
     * @return the value of user.access_secret
     *
     * @mbggenerated
     */
    public String getAccessSecret() {
        return accessSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.access_secret
     *
     * @param accessSecret the value for user.access_secret
     *
     * @mbggenerated
     */
    public void setAccessSecret(String accessSecret) {
        this.accessSecret = accessSecret == null ? null : accessSecret.trim();
    }
}