package com.send.sms.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.send.sms.pojo.Task;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    Task selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tasks
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Task record);
    
    List<Task> selectTaskByUsername(@Param("username") String username);
    
    //根据开始时间和结束时间查询任务
    List<Task> getSomeTaskByBeTime(@Param("begintime")String begintime,@Param("endtime") String endtime);
}